version: "3"

services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    env_file: .env
    image: mariadb_im
    restart: always
    ports:
      - 42:42
  nginx:
    build: ./nginx
    container_name: nginx
    env_file: .env
    image: nginx_im
    ports:
      - 443:443
    restart: on-failure