version: "3"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    image: mariadb_im
    restart: always
    ports:
      - 3306:3306
    networks:
      - net
    volumes:
      - /home/ozahid-/data/mariadb:/var/lib/mysql
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file: .env
    image: nginx_im
    depends_on:
      - wordpress
    ports:
      - 443:443
    restart: on-failure
    volumes:
      - /home/ozahid-/data/wpgx:/var/www/html
    networks:
      - net
  wordpress:
    build:  ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    image: wordpress_im
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    restart: always
    volumes:
      - /home/ozahid-/data/wpgx:/var/www/html
    networks:
      - net
networks:
  net:
    